# Generated by Django 6.0.3 on 2026-04-01 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employe',
            old_name='lieu_de_naissance',
            new_name='lieu_de_residence',
        ),
    ]
